name: Deploy to Azure VM

on:
 push:
    branches:
      - main

jobs:
 deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Copy files to Azure VM
      run: |
        scp -r . ${{ secrets.SSH_USERNAME }}@your-azure-vm:/path/to/destination

    - name: Run Docker Compose on Azure VM
      run: |
        ssh ${{ secrets.SSH_USERNAME }}@your-azure-vm "cd /path/to/destination && docker-compose up -d"
